version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      include:
        - "*"
    groups:
      lupa:
        patterns:
          - "lupa"
      other-python-packages:
        patterns:
          - "*"
        exclude-patterns:
          - "lupa"
  - package-ecosystem: "pip"
    directory: "/.github"  # packages only used in CI (relink)
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      include:
        - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      include:
        - "*"
