version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      include:
        - "*"
    groups:
      python-packages:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/.github"  # packages only used in CI (relink)
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      include:
        - "*"
