name: Build All

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:

  build-msys2:
    permissions:
      id-token: write
      attestations: write

    uses: ./.github/workflows/build-msys2.yaml


  build-msbuild:
    permissions:
      id-token: write
      attestations: write

    uses: ./.github/workflows/build-msbuild.yaml


  relink:
    needs: [build-msys2, build-msbuild]
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write

    steps:
      - name: Install python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.14'

      - name: Checkout requirements file
        uses: actions/checkout@v6.0.2
        with:
          sparse-checkout: |
            .github/requirements-relink.txt
          sparse-checkout-cone-mode: false

      - name: Install dependencies
        run: |
          pip install -r .github/requirements-relink.txt

      - name: Load lua53-vs2022-win32-dynamic
        uses: actions/download-artifact@v8.0.1
        with:
          name: lua-apclientpp-lua53-vs2022-win32-dynamic

      - name: Patch 5.3 -> 5.3.3r (vs2022-win32-dynamic)
        # TODO: convert this to a reusable workflow
        run: |
          mv lua-apclientpp.dll _lua-apclientpp.dll
          python -m machomachomangler.cmd.redll _lua-apclientpp.dll lua-apclientpp.dll lua53.dll Lua5.3.3r.dll
          python -m mingw_ldd lua-apclientpp.dll --dll-lookup-dirs . | grep lua
          sha256sum _lua-apclientpp.dll lua-apclientpp.dll
          mkdir -p relink/lua533r-vs2022-win32-dynamic
          mv lua-apclientpp.dll relink/lua533r-vs2022-win32-dynamic/

      - name: Store lua533r-vs2022-win32-dynamic
        uses: actions/upload-artifact@v7.0.0
        with:
          name: lua-apclientpp-lua533r-vs2022-win32-dynamic
          path: relink/lua533r-vs2022-win32-dynamic/lua-apclientpp.dll

      - name: Load lua51-vs2022-win32-dynamic
        uses: actions/download-artifact@v8.0.1
        with:
          name: lua-apclientpp-lua51-vs2022-win32-dynamic

      - name: Patch 5.1 -> 51 (vs2022-win32-dynamic)
        run: |
          mv lua-apclientpp.dll _lua-apclientpp.dll
          python -m machomachomangler.cmd.redll _lua-apclientpp.dll lua-apclientpp.dll lua5.1.dll lua51.dll
          python -m mingw_ldd lua-apclientpp.dll --dll-lookup-dirs . | grep lua
          sha256sum _lua-apclientpp.dll lua-apclientpp.dll
          mkdir -p relink/lua51-51-vs2022-win32-dynamic
          mv lua-apclientpp.dll relink/lua51-51-vs2022-win32-dynamic/

      - name: Store lua51-51-vs2022-win32-dynamic
        uses: actions/upload-artifact@v7.0.0
        with:
          name: lua-apclientpp-lua51-51-vs2022-win32-dynamic
          path: relink/lua51-51-vs2022-win32-dynamic/lua-apclientpp.dll

      - name: Attest relinked DLLs
        uses: actions/attest@v4.1.0
        with:
          subject-path: 'relink/*/lua-apclientpp.dll'

  license-copy-paste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - name: Copy Pasta
        run: |
          cat LICENSE > lua-apclientpp-license.txt
          echo -e "\n\n# apclientpp\n" >> lua-apclientpp-license.txt
          cat subprojects/apclientpp/LICENSE >> lua-apclientpp-license.txt
          echo -e "\n\n# Asio C++ Library\n" >> lua-apclientpp-license.txt
          cat subprojects/asio/COPYING >> lua-apclientpp-license.txt
          echo -e "\n\n# JSON for Modern C++\n" >> lua-apclientpp-license.txt
          cat subprojects/json/LICENSE.MIT >> lua-apclientpp-license.txt
          echo -e "\n\n# Valijson\n" >> lua-apclientpp-license.txt
          cat subprojects/valijson/LICENSE >> lua-apclientpp-license.txt
          echo -e "\n\n# WebSocket++\n" >> lua-apclientpp-license.txt
          cat subprojects/websocketpp/websocketpp/COPYING >> lua-apclientpp-license.txt
          echo -e "\n\n# black-sliver/wswrap\n" >> lua-apclientpp-license.txt
          cat subprojects/wswrap/LICENSE >> lua-apclientpp-license.txt

      - name: Store
        uses: actions/upload-artifact@v7.0.0
        with:
          name: lua-apclientpp-license
          path: lua-apclientpp-license.txt
