name: Build

on: workflow_dispatch

jobs:

  build-msys2:

    strategy:
      # NOTE: setting up msys takes longer than building, so we don't matrix the lua versions
      # TODO: use sub-action to make this cleaner
      matrix:
        sys:
          - clang32
          - clang64
          - mingw32
          - mingw64
          - ucrt64

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install MSYS ${{matrix.sys}}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          # update: true
          pacboy: openssl:p lua:p lua51:p lua53:p
          # NOTE: msys does not have lua52, so we will have to build from source or download prebuilts

      - name: Install gcc
        if: ${{ !startsWith(matrix.sys, 'clang') }}
        run: |
          pacboy -S gcc:p

      - name: Install clang + gcc-wrapper
        if: ${{ startsWith(matrix.sys, 'clang') }}
        run: |
          pacboy -S gcc-compat:p

      - name: Build lua51-dynamic
        run: |
          rm -f *.dll
          ./build_posix.sh lua51

      - name: Store lua51-dynamic
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-lua51-${{matrix.sys}}-dynamic
          path: lua-apclientpp.dll

      - name: Build lua51-static
        run: |
          rm -f *.dll
          ./build_posix.sh lua51 static

      - name: Store lua51-static
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-lua51-${{matrix.sys}}-dynamic
          path: lua-apclientpp.dll

      - name: Build lua53-dynamic
        run: |
          rm -f *.dll
          ./build_posix.sh lua53

      - name: Store lua53-dynamic
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-lua53-${{matrix.sys}}-dynamic
          path: lua-apclientpp.dll

      - name: Build lua53-static
        run: |
          rm -f *.dll
          ./build_posix.sh lua53 static

      - name: Store lua53-static
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-lua53-${{matrix.sys}}-static
          path: lua-apclientpp.dll

      - name: Build lua54-dynamic
        run: |
          rm -f *.dll
          ./build_posix.sh lua54

      - name: Store lua54-dynamic
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-lua54-${{matrix.sys}}-dynamic
          path: lua-apclientpp.dll

      - name: Build lua54-static
        run: |
          rm -f *.dll
          ./build_posix.sh lua54 static

      - name: Store lua54-static
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-lua54-${{matrix.sys}}-static
          path: lua-apclientpp.dll
