name: Build All

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Debug or Release Build'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
  push:
    tags:
      - 'v*'

jobs:

  build-msys2:
    uses: ./.github/workflows/build-msys2.yaml
    with:
      configuration: ${{ inputs.configuration }}

  build-msbuild:
    uses: ./.github/workflows/build-msbuild.yaml
    with:
      configuration: ${{ inputs.configuration }}

  relink:
    needs: [build-msys2, build-msbuild]
    runs-on: ubuntu-latest

    steps:
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade machomachomangler mingw_ldd

      - name: Load lua53-vs2022-win32-dynamic
        uses: actions/download-artifact@v4
        with:
          name: lua-apclientpp-lua53-vs2022-win32-dynamic

      - name: Patch 5.3 -> 5.3.3r (vs2022-win32-dynamic)
        # TODO: convert this to a reusable workflow
        run: |
          mv lua-apclientpp.dll _lua-apclientpp.dll
          python -m machomachomangler.cmd.redll _lua-apclientpp.dll lua-apclientpp.dll lua53.dll Lua5.3.3r.dll
          python -m mingw_ldd lua-apclientpp.dll --dll-lookup-dirs . | grep lua

      - name: Store lua533r-vs2022-win32-dynamic
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua533r-vs2022-win32-dynamic
          path: lua-apclientpp.*

      - name: Load lua51-vs2022-win32-dynamic
        uses: actions/download-artifact@v4
        with:
          name: lua-apclientpp-lua51-vs2022-win32-dynamic

      - name: Patch 5.1 -> 51 (vs2022-win32-dynamic)
        run: |
          mv lua-apclientpp.dll _lua-apclientpp.dll
          python -m machomachomangler.cmd.redll _lua-apclientpp.dll lua-apclientpp.dll lua5.1.dll lua51.dll
          python -m mingw_ldd lua-apclientpp.dll --dll-lookup-dirs . | grep lua

      - name: Store lua51-51-vs2022-win32-dynamic
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua51-51-vs2022-win32-dynamic
          path: lua-apclientpp.*


  license-copy-paste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy Pasta
        run: |
          cat LICENSE > lua-apclientpp-license.txt
          echo -e "\n\n# apclientpp\n" >> lua-apclientpp-license.txt
          cat subprojects/apclientpp/LICENSE >> lua-apclientpp-license.txt
          echo -e "\n\n# Asio C++ Library\n" >> lua-apclientpp-license.txt
          cat subprojects/asio/COPYING >> lua-apclientpp-license.txt
          echo -e "\n\n# JSON for Modern C++\n" >> lua-apclientpp-license.txt
          cat subprojects/json/LICENSE.MIT >> lua-apclientpp-license.txt
          echo -e "\n\n# Valijson\n" >> lua-apclientpp-license.txt
          cat subprojects/valijson/LICENSE >> lua-apclientpp-license.txt
          echo -e "\n\n# WebSocket++\n" >> lua-apclientpp-license.txt
          cat subprojects/websocketpp/websocketpp/COPYING >> lua-apclientpp-license.txt
          echo -e "\n\n# black-sliver/wswrap\n" >> lua-apclientpp-license.txt
          cat subprojects/wswrap/LICENSE >> lua-apclientpp-license.txt

      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-license
          path: lua-apclientpp-license.txt
