name: Build

on: workflow_dispatch

jobs:

  build-msys2:

    strategy:
      # NOTE: setting up msys takes longer than building, so we don't matrix the lua versions
      # TODO: use sub-action to make this cleaner
      matrix:
        sys:
          - clang32
          - clang64
          - mingw32
          - mingw64
          - ucrt64
        lua:
          - 5.1
          #- 5.2  # needs manual install
          - 5.3
          - 5.4

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    env:
      DEFAULT_LUA: 5.4

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set ENV
        shell: bash
        run: |
          export LUA_NUMBER=`echo ${{matrix.lua}} | sed 's/\.//'`
          echo "LUA_NAME=lua$LUA_NUMBER" >> $GITHUB_ENV
          echo "LUA_VERSION=lua${{matrix.lua}}" >> $GITHUB_ENV

      - name: Set env (PKG, versioned lua)
        if: ${{ matrix.lua != env.DEFAULT_LUA }}
        shell: bash
        run: |
          echo "LUA_PKG=${{env.LUA_NAME}}:p" >> $GITHUB_ENV

      - name: Set env (PKG, default lua)
        if: ${{ matrix.lua == env.DEFAULT_LUA }}
        shell: bash
        run: |
          echo "LUA_PKG=lua:p" >> $GITHUB_ENV

      - name: Install MSYS ${{matrix.sys}} + gcc
        if: ${{ !startsWith(matrix.sys, 'clang') }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          # update: true
          pacboy: openssl:p pkg-config:p gcc:p binutils:p ${{env.LUA_PKG}}

      - name: Install MSYS ${{matrix.sys}} + clang + gcc-wrapper
        if: ${{ startsWith(matrix.sys, 'clang') }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          # update: true
          pacboy: openssl:p pkg-config:p gcc-compat:p ${{env.LUA_PKG}}

      - name: Build ${{env.LUA_NAME}}-dynamic
        run: |
          rm -f *.dll
          ./build_posix.sh ${{env.LUA_VERSION}}

      - name: Store ${{env.LUA_NAME}}-dynamic
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-${{env.LUA_NAME}}-${{matrix.sys}}-dynamic
          path: lua-apclientpp.dll

      - name: Build ${{env.LUA_NAME}}-static
        run: |
          rm -f *.dll
          ./build_posix.sh ${{env.LUA_VERSION}} static

      - name: Store ${{env.LUA_NAME}}-static
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-${{env.LUA_NAME}}-${{matrix.sys}}-static
          path: lua-apclientpp.dll
