name: Build MSBuild

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-msbuild:
    # TODO: automated testing
    env:
      BUILD_PLATFORM: "x86"
      BUILD_CONFIGURATION: Release
      OPENSSL_BUILD_PLATFORM: VC-WIN32
      ARCH: win32
      LUA52_VERSION: "5.2.4"
      LUA53_VERSION: "5.3.6"
      LUA54_VERSION: "5.4.7"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          #- os: windows-2019
          #  sln: vs2015
          #- os: windows-2019
          #  sln: vs2017
          - os: windows-2022
            sln: vs2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools v140
        if: |
          matrix.sln == 'vs2015'
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_BuildTools.exe" -OutFile "vs_BuildTools.exe"
          Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList "--add", "Microsoft.VisualStudio.Component.VC.140", "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru

      - name: Install build tools v141
        if: |
          matrix.sln == 'vs2017'
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_BuildTools.exe" -OutFile "vs_BuildTools.exe"
          Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList "--add", "Microsoft.VisualStudio.Component.VC.v141.x86.x64", "--add", "Microsoft.VisualStudio.Component.VC.v141.CLI.Support", "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru

      - name: MSVC Dev Cmd 14.0
        uses: ilammy/msvc-dev-cmd@v1
        if: |
          matrix.sln == 'vs2015'
        with:
          arch: ${{env.ARCH}}
          toolset: '14.0'

      - name: MSVC Dev Cmd 14.1
        uses: ilammy/msvc-dev-cmd@v1
        if: |
          matrix.sln == 'vs2017'
        with:
          arch: ${{env.ARCH}}
          toolset: '14.1'

      - name: MSVC Dev Cmd (Default)
        uses: ilammy/msvc-dev-cmd@v1
        if: |
          matrix.sln == 'vs2022'
        with:
          arch: ${{env.ARCH}}

      - name: Install NASM
        uses: ilammy/setup-nasm@v1

      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1

      - name: Build OpenSSL
        run: |
          cd dep
          git clone -b OpenSSL_1_1_1-stable --depth 1 https://github.com/openssl/openssl.git
          cd openssl
          md ${{env.BUILD_PLATFORM}}
          cd ${{env.BUILD_PLATFORM}}
          perl ..\Configure ${{env.OPENSSL_BUILD_PLATFORM}} no-shared
          nmake /S

      - name: Build zlib
        run: |
          cd dep
          git clone -b v1.3.1 --depth 1 https://github.com/madler/zlib.git
          cd zlib
          nmake -f win32/Makefile.msc
          md ${{env.BUILD_PLATFORM}}
          move *.dll ${{env.BUILD_PLATFORM}}
          move *.lib ${{env.BUILD_PLATFORM}}

      - name: Build Lua 5.2
        id: build52
        uses: black-sliver/lua-build@9a5cd4d6b10d1aa6d1e4b7ff6d6a1b6944278d3f
        with:
          name: "lua52"
          version: "${{ env.LUA52_VERSION }}"

      - name: Build Lua 5.3
        id: build53
        uses: black-sliver/lua-build@9a5cd4d6b10d1aa6d1e4b7ff6d6a1b6944278d3f
        with:
          name: "lua53"
          version: "${{ env.LUA53_VERSION }}"

      - name: Build Lua 5.4
        id: build54
        uses: black-sliver/lua-build@9a5cd4d6b10d1aa6d1e4b7ff6d6a1b6944278d3f
        with:
          name: "lua54"
          version: "${{ env.LUA54_VERSION }}"

      - name: Move Lua Builds
        run: |
          move ${{ steps.build52.outputs.path }} dep/lua52
          move ${{ steps.build53.outputs.path }} dep/lua53
          move ${{ steps.build54.outputs.path }} dep/lua54
          dir dep

      - name: Add MSBuild to PATH
        if: |
          matrix.sln == 'vs2017'
        uses: microsoft/setup-msbuild@v2

      - name: Build for Lua 5.1 Dynamic
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.sln}}/lua-apclientpp-51-dynamic.sln /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua51
          move ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua-apclientpp-51-dynamic.dll ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua51\lua-apclientpp.dll

      - name: Store Lua 5.1 Dynamic
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua51-${{matrix.sln}}-${{env.ARCH}}-dynamic
          path: ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua51\lua-apclientpp.dll
          if-no-files-found: error

      - name: Build for Lua 5.2 Dynamic
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.sln}}/lua-apclientpp-52-dynamic.sln /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua52
          move ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua-apclientpp-52-dynamic.dll ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua52\lua-apclientpp.dll

      - name: Store Lua 5.2 Dynamic
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua52-${{matrix.sln}}-${{env.ARCH}}-dynamic
          path: ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua52\lua-apclientpp.dll
          if-no-files-found: error

      - name: Build for Lua 5.2 Static
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.sln}}/lua-apclientpp-52-static.sln /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua52-static
          move ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua-apclientpp-52-static.dll ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua52-static\lua-apclientpp.dll

      - name: Store Lua 5.2 Static
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua52-${{matrix.sln}}-${{env.ARCH}}-static
          path: ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua52-static\lua-apclientpp.dll
          if-no-files-found: error

      - name: Build for Lua 5.3 Dynamic
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.sln}}/lua-apclientpp-53-dynamic.sln /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua53
          move ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua-apclientpp-53-dynamic.dll ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua53\lua-apclientpp.dll

      - name: Store Lua 5.3 Dynamic
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua53-${{matrix.sln}}-${{env.ARCH}}-dynamic
          path: ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua53\lua-apclientpp.dll
          if-no-files-found: error

      - name: Build for Lua 5.3 Static
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.sln}}/lua-apclientpp-53-static.sln /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua53-static
          move ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua-apclientpp-53-static.dll ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua53-static\lua-apclientpp.dll

      - name: Store Lua 5.3 Static
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua53-${{matrix.sln}}-${{env.ARCH}}-static
          path: ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua53-static\lua-apclientpp.dll
          if-no-files-found: error

      - name: Build for Lua 5.4 Dynamic
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.sln}}/lua-apclientpp-54-dynamic.sln /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua54
          move ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua-apclientpp-54-dynamic.dll ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua54\lua-apclientpp.dll

      - name: Store Lua 5.4 Dynamic
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua54-${{matrix.sln}}-${{env.ARCH}}-dynamic
          path: ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua54\lua-apclientpp.dll
          if-no-files-found: error

      - name: Build for Lua 5.4 Static
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.sln}}/lua-apclientpp-54-static.sln /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua54-static
          move ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua-apclientpp-54-static.dll ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua54-static\lua-apclientpp.dll

      - name: Store Lua 5.4 Static
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua54-${{matrix.sln}}-${{env.ARCH}}-static
          path: ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua54-static\lua-apclientpp.dll
          if-no-files-found: error

      - name: Install 32bit Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          architecture: 'x86'
          cache: 'pip'

      - name: Install test dependencies
        run: >
          pip install
          -r test/requirements.txt
          -r test/requirements-dev.txt

      - name: Setup test
        run: |
          copy ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua54-static\lua-apclientpp.dll .

      - name: Run tests
        run: >
          pytest
        # -n4
