name: Build MSBuild

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-msbuild:
    # TODO: automated testing
    env:
      BUILD_PLATFORM: "x86"
      BUILD_CONFIGURATION: Release
      OPENSSL_BUILD_PLATFORM: VC-WIN32
      ARCH: win32
      LUA52_VERSION: "5.2.4"
      LUA53_VERSION: "5.3.6"
      LUA54_VERSION: "5.4.7"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            sln: vs2015
          - os: windows-2019
            sln: vs2017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools v140
        if: |
          matrix.sln == 'vs2015'
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_BuildTools.exe"
          Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList "--add", "Microsoft.VisualStudio.Component.VC.140", "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru


      - uses: ilammy/setup-nasm@v1

      - uses: ilammy/msvc-dev-cmd@v1
        if: |
          matrix.sln == 'vs2017'
        with:
          arch: ${{env.ARCH}}

      - uses: ilammy/msvc-dev-cmd@v1
        if: |
          matrix.sln == 'vs2015'
        with:
          arch: ${{env.ARCH}}
          toolset: '14.0'

      - uses: shogo82148/actions-setup-perl@v1

      - name: Build OpenSSL
        run: |
          cd dep
          git clone -b OpenSSL_1_1_1-stable --depth 1 https://github.com/openssl/openssl.git
          cd openssl
          md x86
          cd x86
          perl ..\Configure ${{env.OPENSSL_BUILD_PLATFORM}} no-shared
          nmake /S

      - name: Build zlib
        run: |
          cd dep
          git clone -b v1.3.1 --depth 1 https://github.com/madler/zlib.git
          cd zlib
          nmake -f win32/Makefile.msc
          md ${{env.BUILD_PLATFORM}}
          move *.dll ${{env.BUILD_PLATFORM}}
          move *.lib ${{env.BUILD_PLATFORM}}

      - name: Build Lua 5.2
        id: build52
        uses: black-sliver/lua-build@9a5cd4d6b10d1aa6d1e4b7ff6d6a1b6944278d3f
        with:
          name: "lua52"
          version: "${{ env.LUA52_VERSION }}"

      - name: Build Lua 5.3
        id: build53
        uses: black-sliver/lua-build@9a5cd4d6b10d1aa6d1e4b7ff6d6a1b6944278d3f
        with:
          name: "lua53"
          version: "${{ env.LUA53_VERSION }}"

      - name: Build Lua 5.4
        id: build54
        uses: black-sliver/lua-build@9a5cd4d6b10d1aa6d1e4b7ff6d6a1b6944278d3f
        with:
          name: "lua54"
          version: "${{ env.LUA54_VERSION }}"

      - name: Move Lua Builds
        run: |
          move ${{ steps.build52.outputs.path }} dep/lua52
          move ${{ steps.build53.outputs.path }} dep/lua53
          move ${{ steps.build54.outputs.path }} dep/lua54
          dir dep

      - name: Add MSBuild to PATH
        if: |
          matrix.sln == 'vs2017'
        uses: microsoft/setup-msbuild@v2

      - name: Build for Lua 5.1 Dynamic
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.sln}}/lua-apclientpp-51-dynamic.sln /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua51
          move ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua-apclientpp-51-dynamic.dll ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua51\lua-apclientpp.dll

      - name: Store Lua 5.1 Dynamic
        uses: actions/upload-artifact@v4
        with:
          name: lua-apclientpp-lua51-${{matrix.sln}}-${{env.ARCH}}-dynamic
          path: ${{matrix.sln}}\${{env.BUILD_CONFIGURATION}}\lua51\lua-apclientpp.dll
