# build with GCC to see if source code is valid
name: CI

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install coreutils build-essential libssl-dev liblua5.4-dev

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: ./build_posix.sh
