name: Check for typos

on:
  push:
  pull_request:

permissions: {}

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579  # v2.2
