name: MSBuild

on: workflow_dispatch

jobs:

  build-51-msbuild:
    env:
      SOLUTION_FILE_PATH: .
      BUILD_CONFIGURATION: Release
      BUILD_PLATFORM: "x86"
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build Project
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:Platform=${{env.BUILD_PLATFORM}}

      - name: dir
        run: dir

      - name: Store
        uses: actions/upload-artifact@v3
        with:
          name: lua-apclientpp-51-msbuild
          path: Release

